### ISSUE TITLE
Docs issues

### ISSUE THREAD

**Issue by temp** [puli/puli#25]
Since playing with types I noticed that the docs at docs.puli.io still describe only the old tag mechanism.
But I guess you are aware of that ;-)

Another thing I'm missing is a schema definition for puli.json, like on getcomposer.org.
I have seen that with "type --package <package>" puli shows the defined types for a package.
But how can I define types package-wise? I guess via puli.json, but I haven't found anything about it.

**Comment by webmozart** [comment]
Yes, I'm planning to adapt the docs this week to use the CLI everywhere instead of editing the puli.json by hand.

I originally planned to put the schema definition online just like on getcomposer.org, but I don't think anymore I will do that. I really want people to use the CLI instead of editing puli.json by hand. The CLI prevents many mistakes that you can do if you edit by hand.

> But how can I define types package-wise?

You cannot. Each package is responsible for its own resource mappings, types and bindings. So the real answer is: Check out the package, define the type there, and push the modified puli.json.

**Comment by temp** [comment]
Ok, makes sense. Thanks for the clarification!
